apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://172.17.0.3:32021 # dev
  project: default
  source:
  # It's possible to override helm values through different ways such as "valueFiles", "values", "valuesObject" and "parameters". 
  # Values injections have the following order of precedence parameters > valuesObject > values > valueFiles > helm repository values.yaml Or rather
    helm:
      releaseName: application-from-helm
          #      valueFiles:
          #        - custom-values.yaml
          #      values: |
          #        replicaCount: 3
          #      valuesObject:
          #        replicaCount: 5
          #      parameters:
          #        - name: "replicaCount"
          #          value: "1"
    path: argocd-applications/helm/nginx
    repoURL: https://github.com/ITBeyder/ArgoCD-In-Minikube-Multi-Cluster.git
    targetRevision: main
