apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-helm
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://172.17.0.3:32021 # dev
  project: default
  source:
    directory:
      # exclude: 'service.yml'
      # include: '{serviceaccount.yml,service.yml}'
      recurse: true # will install also yamls inside "sub-directory"
    path: argocd-applications/directoryOfmanifests
    repoURL: https://github.com/ITBeyder/ArgoCD-In-Minikube-Multi-Cluster.git
    targetRevision: main
